version: 1

before:
  hooks:
  - go mod tidy

builds:
- main: cmd/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin

archives:
- format: binary

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
